
studio_cfg: "config/default.yaml"

templates:
  sg_version_rep:
    pattern: "{color}_{resolution}_{ext}"
    required_tokens: [color, resolution, ext]
    transforms:
      color: ["lowercase"]
      resolution: ["lowercase"]
      ext: ["lowercase"]

  sg_version_name:
    pattern: "{shotCode}_{task}_{sg_version_rep}_{descriptor}_v{version}"
    required_tokens: [shotCode, task, descriptor, version]
    optional_tokens: [show, sg_version_rep]
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      task: ["lowercase"]
      descriptor: ["lowercase"]
      version: ["version_format"]

  published_seq_files:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{pub_dir}/{sg_version_name}/{ext}/{sg_version_name}.{padding}.{ext}"
    required_tokens: [root, seq, shotCode, task, ext]
    optional_tokens: [padding, pub_dir, sg_version_name]
    default_tokens:
      pub_dir: "pub_dir"
      padding: 4 
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]

  published_seq_stereo_files:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{pub_dir}/{sg_version_name}/{ext}/{sg_version_name}_{eye}.{padding}.{ext}"
    required_tokens: [root, seq, shotCode, task, ext]
    optional_tokens: [eye, padding, pub_dir, sg_version_name]
    default_tokens:
      pub_dir: "pub_dir"
      padding: 4 
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      eye: ["lowercase"]
  
  published_files:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{pub_dir}/{sg_version_name}/{ext}/{sg_version_name}.{ext}"
    required_tokens: [root, seq, shotCode, task, ext]
    optional_tokens: [pub_dir, sg_version_name]
    default_tokens:
      pub_dir: "pub_dir"
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      eye: ["lowercase"]

  work_dir:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{work_dir}/"
    required_tokens: [root, seq, shotCode, task]
    optional_tokens: [show, work_dir]
    default_tokens:
      work_dir: "work_dir"
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]

  work_files:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{work_dir}/{ext}/{show}_{shotCode}_{task}_{descriptor}_v{version}.{ext}"
    required_tokens: [root, seq, shotCode, task, version, ext]
    optional_tokens: [show, work_dir, descriptor]
    default_tokens:
      work_dir: "work_dir"
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      version: ["version_format"]

  work_render:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{work_dir}/render/v{version}/{show}_{shotCode}_{task}_{descriptor}_v{version}_{eye}.{padding}.{ext}"
    required_tokens: [root, seq, shotCode, task, version, ext]
    optional_tokens: [show, work_dir, descriptor, eye, padding]
    default_tokens:
      work_dir: "work_dir"
      padding: 4 
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      version: ["version_format"]

  work_file:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{work_dir}/render/v{version}/{show}_{shotCode}_{task}_{descriptor}_v{version}.{ext}"
    required_tokens: [root, seq, shotCode, task, version, ext]
    optional_tokens: [show, work_dir, descriptor]
    default_tokens:
      work_dir: "work_dir"
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      version: ["version_format"]

  precomp_render:
    pattern: "{root}/seq/{seq}/{shotCode}/{task}/{work_dir}/precomp/{preset}/v{version}/{show}_{shotCode}_{task}_{preset}_v{version}_{eye}.{padding}.{ext}"
    required_tokens: [root, seq, shotCode, task, version, preset, ext]
    optional_tokens: [show, work_dir, eye, padding]
    default_tokens:
      work_dir: "work_dir"
      padding: 4
    transforms:
      show:     ["uppercase"]
      shotCode: ["uppercase"]
      preset:   ["lowercase"]
      version:  ["version_format"]
      ext:      ["lowercase"]