
studio_cfg: "config/default.yaml"

templates:
  sg_version_rep:
    pattern: "{color}_{resolution}_{ext}"
    required_tokens: [color, resolution, ext]
    transforms:
      color: ["lowercase"]
      resolution: ["lowercase"]
      ext: ["lowercase"]

  sg_version_name:
    pattern: "{show}_{shotCode}_{task}_{sg_version_rep}_{descriptor}_v{version}"
    required_tokens: [shotCode, task, descriptor, version]
    optional_tokens: [show, sg_version_rep]
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      task: ["lowercase"]
      descriptor: ["lowercase"]
      version: ["version_format"]

  published_files:
    pattern: "{root}/{seq}/{shotCode}/{task}/{pub_dir}/{sg_version_name}/{sg_version_name}_{eye}.{padding}.{ext}"
    required_tokens: [root, seq, shotCode, task, ext]
    optional_tokens: [eye, padding, pub_dir, sg_version_name]
    default_tokens:
      pub_dir: "pub_dir"
      padding: 4 
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      eye: ["lowercase"]

  work_files:
    pattern: "{root}/{seq}/{shotCode}/{task}/{work_dir}/{show}_{shotCode}_{task}_{descriptor}_v{version}.{ext}"
    required_tokens: [root, seq, shotCode, task, version, ext]
    optional_tokens: [show, work_dir, descriptor]
    default_tokens:
      work_dir: "work_dir"
    transforms:
      show: ["uppercase"]
      shotCode: ["uppercase"]
      ext: ["lowercase"]
      version: ["version_format"]
